version: '3'

services:
    book-library:
        build: ./book-library
        volumes:
            - ./book-library:/usr/src/app
        ports:
            - 5001:80

    website:
        build: ./website
        volumes:
            - ./website:/var/www/html
        ports:
            - 5000:80
        depends_on:
            - book-library
